export const nigerianShippingRates = [
    { destination: 'Abia', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Adamawa', doorToDoor: 7.00, collection: 7.00, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Akwa Ibom', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Anambra', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Bauchi', doorToDoor: 7.00, collection: 7.00, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Bayelsa', doorToDoor: 7.00, collection: 7.00, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Benue', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Borno', doorToDoor: 7.50, collection: 7.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Cross River', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Delta', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Ebonyi', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Edo', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Ekiti', doorToDoor: 6.20, collection: 6.20, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Enugu', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Gombe', doorToDoor: 7.50, collection: 7.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Imo', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Jigawa', doorToDoor: 7.50, collection: 7.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Kaduna', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Kano', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Katsina', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Kebbi', doorToDoor: 7.00, collection: 7.00, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Kogi', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Kwara', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Lagos', doorToDoor: 6.00, collection: 6.00, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Nassarawa', doorToDoor: 7.00, collection: 7.00, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Niger', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Ogun', doorToDoor: 6.20, collection: 6.20, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Ondo', doorToDoor: 6.20, collection: 6.20, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Osun', doorToDoor: 6.20, collection: 6.20, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Oyo', doorToDoor: 6.20, collection: 6.20, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Plateau', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Rivers', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Sokoto', doorToDoor: 7.50, collection: 7.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Taraba', doorToDoor: 7.50, collection: 7.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Yobe', doorToDoor: 7.50, collection: 7.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Zamfara', doorToDoor: 7.50, collection: 7.50, minWeight: 1, avgDelivery: '5-10' },
    { destination: 'Federal Capital Territory (Abuja)', doorToDoor: 6.50, collection: 6.50, minWeight: 1, avgDelivery: '5-10' },
];

export const usShippingRates = [
    { destination: 'Abia', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Adamawa', doorToDoor: 8.00, minWeight: 30 },
    { destination: 'Akwa Ibom', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Anambra', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Bauchi', doorToDoor: 8.00, minWeight: 30 },
    { destination: 'Bayelsa', doorToDoor: 8.00, minWeight: 30 },
    { destination: 'Benue', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Borno', doorToDoor: 8.50, minWeight: 20 },
    { destination: 'Cross River', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Delta', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Ebonyi', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Edo', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Ekiti', doorToDoor: 6.50, minWeight: 20 },
    { destination: 'Enugu', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Gombe', doorToDoor: 8.50, minWeight: 20 },
    { destination: 'Imo', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Jigawa', doorToDoor: 8.50, minWeight: 20 },
    { destination: 'Kaduna', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Kano', doorToDoor: 7.50, minWeight: 20 },
    { destination: 'Katsina', doorToDoor: 7.50, minWeight: 20 },
    { destination: 'Kebbi', doorToDoor: 8.00, minWeight: 20 },
    { destination: 'Kogi', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Kwara', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Lagos', doorToDoor: 4.50, minWeight: 10 },
    { destination: 'Nassarawa', doorToDoor: 8.00, minWeight: 20 },
    { destination: 'Niger', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Ogun', doorToDoor: 6.50, minWeight: 20 },
    { destination: 'Ondo', doorToDoor: 6.50, minWeight: 20 },
    { destination: 'Osun', doorToDoor: 6.50, minWeight: 20 },
    { destination: 'Oyo', doorToDoor: 6.50, minWeight: 20 },
    { destination: 'Plateau', doorToDoor: 7.50, minWeight: 30 },
    { destination: 'Rivers', doorToDoor: 7.20, minWeight: 20 },
    { destination: 'Sokoto', doorToDoor: 8.50, minWeight: 20 },
    { destination: 'Taraba', doorToDoor: 8.50, minWeight: 20 },
    { destination: 'Yobe', doorToDoor: 8.50, minWeight: 20 },
    { destination: 'Zamfara', doorToDoor: 8.50, minWeight: 20 },
    { destination: 'Federal Capital Territory (Abuja)', doorToDoor: 7.20, minWeight: 10 },
];

export const electronicsPrices = [
    { item: '19″ TV', price: 120 },
    { item: '24″ TV', price: 160 },
    { item: '32″ TV', price: 180 },
    { item: '37″ TV', price: 200 },
    { item: '40″ TV', price: 230 },
    { item: '42″ TV', price: 260 },
    { item: '46″ TV', price: 300 },
    { item: '50″ TV', price: 350 },
    { item: '55″ TV', price: 400 },
    { item: '65″ TV', price: 450 },
    { item: '75″ TV', price: 550 },
    { item: 'Laptop (15–17″)', price: 100 },
    { item: 'Computer / Desktop', price: 150 },
    { item: 'Mobile Phone (per unit)', price: 30 },
    { item: 'iPad / Tablet', price: 60 },
];

export const nigerianCitiesToStates: { [city: string]: string } = {
  'Aba': 'Abia',
  'Abuja': 'Federal Capital Territory (Abuja)',
  'Ado-Ekiti': 'Ekiti',
  'Akure': 'Ondo',
  'Asaba': 'Delta',
  'Awka': 'Anambra',
  'Benin City': 'Edo',
  'Calabar': 'Cross River',
  'Enugu': 'Enugu',
  'Ibadan': 'Oyo',
  'Ilorin': 'Kwara',
  'Kano': 'Kano',
  'Lagos': 'Lagos',
  'Onitsha': 'Anambra',
  'Owerri': 'Imo',
  'Port Harcourt': 'Rivers',
  'Uyo': 'Akwa Ibom',
  'Warri': 'Delta'
};
